### ISSUE TITLE
Add language chooser menu

### ISSUE THREAD

**Issue by brylie** [brylie/wagtail-social-network#39]
Continued from #35 

Now that we are supporting multi-lingual static content, we want users to be able to choose the desired language from a list of supported languages. Each time we add a new language translation, we will ensure the language list is (automatically?) updated.

## Task

- [ ] add a language chooser select menu to the site navigation
- [ ] ensure that all supported languages are (automatically) included in the language chooser select menu

## Resources

- Django docs: [Switching language in templates](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#switching-language-in-templates)

**Comment by Upasanadhameliya** [comment]
@brylie I would like to work on this issue, please assign me the same

**Comment by brylie** [comment]
Very cool! The language selection menu will make our social networking app relevant to more communities. I've assigned you @Upasanadhameliya.

**Comment by Upasanadhameliya** [comment]
@brylie 
- Firstly, I think that we would require a `locale` folder containing `.po` files of all languages, generated through `makemessages` (see: [localization](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#localization-how-to-create-language-files)). This would need to be done as the [django inbuilt translation](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#:~:text=Finally%2C%20the%20Django-provided%20base%20translation%20in%20django/conf/locale%20is%20used%20as%20a%20fallback.) translates only selected strings. For example, `password` translation isn't present in the .po files provided by [django](https://github.com/django/django/blob/main/django/conf/locale/de/LC_MESSAGES/django.po), despite the fact that `password` is a frequently occuring string in websites.
- Secondly, it would not be possible to manually provide `translation strings` in `.po` for each language. A workaround for the same might be to use a facility like `Google Translate`, to automatically fill in the missing translations in the `.po` files. We might be able to achieve this using a pre-made solution like [django-autotranslate](https://github.com/ankitpopli1891/django-autotranslate). Although according to me, it has it's fair set of issues and we might have to fork and modify the package for it to be usable.

Any suggestions about the same would be appreciated, in order to determine the trajectory of the process.

**Comment by brylie** [comment]
Let's use the `locale` folder approach with `.po` files rather than machine localization. We can use a service like [Transifex](https://www.transifex.com/) to crowdsource localizations. We can aim for 80% internationalization coverage and create continuation tasks where i18n isn't trivial.

Note: this task is only to generate the initial `.po` files and add the language switching menu with supported languages.

**Comment by Upasanadhameliya** [comment]
@brylie would you like the language chooser menu to be displayed on the `home page` or someplace different? Should I create a new app for the same or add it to any of the existing ones?

**Comment by brylie** [comment]
Let's include the language chooser in the navigation menu, which is always present whenever a user visits any page.

**Comment by Upasanadhameliya** [comment]
There is currently no `navigation menu` present on our site. Would you like me to create one and add an app named `navigation`?

**Comment by brylie** [comment]
Our `base.html`, which should be used to render all of our pages, includes the [`navbar.html`](https://github.com/brylie/wagtail-social-network/blob/develop/project/core/templates/navbar.html). Let's add the language selection menu in the navbar, so it is always available. Alternatively, it might go somewhere else in the `base.html`.
